image_width: 640
image_height: 480
camera_name: scm_rgbd1
camera_matrix:
  rows: 3
  cols: 3
  data: [570, 0, 325, 0, 570, 260, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.329, 0.0971, 0, 0, 0.0653]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [570, 0, 325, 0, 0, 570, 260, 0, 0, 0, 1, 0]
